import { createHash } from "crypto";
import type { CatalogueCandidate } from "@/types";

type Seed={sourceId:string;sourceUrl:string;name:string;franchise:string;character:string;manufacturer:string;series:string;scale:string;releaseYear:number|null;description:string;fallbackImage:string};
type PageMetadata={image:string;description:string};

const SEEDS:Seed[]=[
  {sourceId:"LEGO-76313",sourceUrl:"https://www.lego.com/en-us/product/marvel-logo-minifigures-76313",name:"MARVEL Logo & Minifigures",franchise:"Marvel",character:"The Avengers",manufacturer:"LEGO",series:"LEGO Marvel",scale:"931 pieces",releaseYear:2025,description:"Buildable Marvel logo display set with Captain America, Iron Man, Thor, Black Widow and Hulk minifigures.",fallbackImage:"https://www.lego.com/cdn/product-assets/product.img.pri/76313_Prod.png"},
  {sourceId:"LEGO-71039",sourceUrl:"https://www.lego.com/en-us/product/lego-minifigures-marvel-series-2-71039",name:"LEGO Minifigures Marvel Series 2",franchise:"Marvel",character:"Marvel Studios Characters",manufacturer:"LEGO",series:"Collectible Minifigures",scale:"Minifigure",releaseYear:2023,description:"Collectible blind-box series featuring twelve Marvel Studios characters, each with at least one accessory.",fallbackImage:"https://www.lego.com/cdn/product-assets/product.img.pri/71039_Prod.png"},
  {sourceId:"HRV80",sourceUrl:"https://shop.mattel.com/products/hot-wheels-premium-car-culture-world-tour-alfa-romeo-gtv-6-30-hrv80",name:"Hot Wheels Alfa Romeo GTV 6 3.0",franchise:"Hot Wheels",character:"Alfa Romeo GTV 6 3.0",manufacturer:"Mattel",series:"Hot Wheels Premium Car Culture",scale:"1:64",releaseYear:2025,description:"Premium Car Culture die-cast vehicle with Real Riders tires and a Metal/Metal body and chassis.",fallbackImage:"https://shop.mattel.com/cdn/shop/files/gyrkuyyj5eizduwtbzvt_ea4a53ad-7b81-4b65-bc3d-ca117e6c8427.jpg?v=1755549623"},
  {sourceId:"82500",sourceUrl:"https://funko.com/pop-spider-man-marvel-new-classics/82500.html",name:"Pop! Spider-Man (Marvel New Classics)",franchise:"Marvel",character:"Spider-Man",manufacturer:"Funko",series:"Pop! Marvel New Classics",scale:"3.7 inches",releaseYear:2025,description:"Marvel New Classics Spider-Man vinyl bobblehead, box number 1422.",fallbackImage:"https://funko.com/on/demandware.static/-/Sites-funko-master-catalog/default/dw5cd6b83e/images/funko/upload/82500_Marvel_NC_SpiderMan_POP_GLAM-WEB.png"},
  {sourceId:"G08115X00",sourceUrl:"https://www.hasbropulse.com/product/marvel-legends-series-marvels-logan/G08115X00",name:"Marvel Legends Series Marvel's Logan",franchise:"Marvel",character:"Logan",manufacturer:"Hasbro",series:"Marvel Legends",scale:"1:12 · 6 inches",releaseYear:2025,description:"Fully articulated X-Men '97 Logan figure with premium design and four pieces.",fallbackImage:"https://cdn.media.amplience.net/i/hasbropulse/G0811_1.png"},
  {sourceId:"787926180213",sourceUrl:"https://mcfarlanetoysstore.com/batman-batman-hush2-7in-figure/",name:"Batman (Batman: Hush 2)",franchise:"DC",character:"Batman",manufacturer:"McFarlane Toys",series:"DC Multiverse",scale:"7 inches",releaseYear:2026,description:"DC Multiverse Batman figure with Ultra Articulation, extra hands, two batarangs and a display base.",fallbackImage:"https://cdn11.bigcommerce.com/s-hlbgbzrg7y/products/3099/images/30869/Batman_Hush_2__30384.1772823449.386.513.jpg?c=1"},
  {sourceId:"G15615X00",sourceUrl:"https://www.hasbropulse.com/product/star-wars-the-black-series-han-solo/G15615X00",name:"Star Wars The Black Series Han Solo",franchise:"Star Wars",character:"Han Solo",manufacturer:"Hasbro",series:"The Black Series",scale:"1:12 · 6 inches",releaseYear:2025,description:"Premium articulated Han Solo figure inspired by Star Wars: A New Hope, including his Episode IV blaster.",fallbackImage:"https://cdn.media.amplience.net/i/hasbropulse/G1561_01"},
  {sourceId:"G09035X00",sourceUrl:"https://www.hasbropulse.com/product/star-wars-the-vintage-collection-luke-skywalker/G09035X00",name:"Star Wars The Vintage Collection Luke Skywalker",franchise:"Star Wars",character:"Luke Skywalker",manufacturer:"Hasbro",series:"The Vintage Collection",scale:"1:18 · 3.75 inches",releaseYear:2025,description:"Collector-grade Luke Skywalker figure inspired by Star Wars: A New Hope with Kenner-style packaging.",fallbackImage:"https://cdn.media.amplience.net/i/hasbropulse/G0903_PROD_SW_TVC_Branding_002"},
  {sourceId:"TAMASHII-15572",sourceUrl:"https://tamashiiweb.com/item/15572/?wovn=en",name:"S.H.Figuarts Son Goku — The Kind-Hearted Saiyan",franchise:"Dragon Ball Z",character:"Son Goku",manufacturer:"Bandai Spirits",series:"S.H.Figuarts",scale:"145 mm",releaseYear:2026,description:"Cell Saga Son Goku with the Dynamic-Movable Shoulder System, interchangeable hands, expressions and head part.",fallbackImage:"https://tamashiiweb.com/storage/images/products/imported/item_0000015572_riFP7xnv_02.jpg"},
  {sourceId:"902815",sourceUrl:"https://www.sideshow.com/collectibles/marvel-iron-man-mark-vi-hot-toys-902815",name:"Iron Man Mark VI Sixth Scale Figure",franchise:"Marvel",character:"Iron Man",manufacturer:"Hot Toys",series:"Movie Masterpiece Series Diecast",scale:"1:6 · 12.83 inches",releaseYear:2016,description:"Diecast Iron Man Mark VI collectible with movie-accurate armor, light-up functions and interchangeable accessories.",fallbackImage:"https://www.sideshow.com/storage/product-images/902815/iron-man-mark-vi_marvel_feature.jpg"}
];

function decode(value:string){return value.replace(/&amp;/g,"&").replace(/&quot;/g,'"').replace(/&#x27;|&#39;/g,"'").replace(/&lt;/g,"<").replace(/&gt;/g,">")}
function meta(html:string,key:string){
  const escaped=key.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");const first=html.match(new RegExp(`<meta[^>]+(?:property|name)=["']${escaped}["'][^>]+content=["']([^"']+)["']`,`i`));const second=html.match(new RegExp(`<meta[^>]+content=["']([^"']+)["'][^>]+(?:property|name)=["']${escaped}["']`,`i`));return decode((first?.[1]||second?.[1]||"").trim());
}
async function metadataOf(seed:Seed):Promise<PageMetadata>{
  try{const response=await fetch(seed.sourceUrl,{headers:{"User-Agent":"TinkerTown-CatalogueBot/1.0 (+admin-curated import)",Accept:"text/html,application/xhtml+xml"},signal:AbortSignal.timeout(10000),cache:"no-store"});if(!response.ok)return {image:seed.fallbackImage,description:seed.description};const html=await response.text();return {image:meta(html,"og:image")||seed.fallbackImage,description:meta(html,"og:description")||seed.description}}catch{return {image:seed.fallbackImage,description:seed.description}}
}

export async function discoverTopCollectibles(importRunId:string){
  const metadata=await Promise.all(SEEDS.map(metadataOf));
  const candidates=SEEDS.map<CatalogueCandidate>((seed,index)=>{const fingerprint=createHash("sha256").update(`top-collectible|${seed.sourceId.toLowerCase()}`).digest("hex");return {id:`web_${fingerprint.slice(0,24)}`,source:"WEB",sourceId:seed.sourceId,sourceUrl:seed.sourceUrl,sourceQuery:"Official manufacturer or authorized product page · Top collector lanes",fingerprint,name:seed.name,franchise:seed.franchise,character:seed.character,manufacturer:seed.manufacturer,series:seed.series,scale:seed.scale,releaseYear:seed.releaseYear,description:metadata[index].description||seed.description,referenceImageUrl:metadata[index].image||seed.fallbackImage,status:"PENDING",importRunId}});
  return {discovered:SEEDS.length,candidates,sources:SEEDS.map(seed=>seed.sourceUrl)};
}
