"use client";

import Image from "next/image";
import { upload } from "@vercel/blob/client";
import { Camera,Check,ImagePlus,PlusCircle,RotateCcw,ScanText,ShieldCheck,Sparkles } from "lucide-react";
import { useEffect,useMemo,useRef,useState } from "react";
import { auth } from "@/lib/firebase";
import { createCommunityFigure } from "@/lib/firestore-data";
import { rankFigureMatches } from "@/lib/figure-match";
import { rankFiguresVisually } from "@/lib/figure-visual-match";
import type { RankedFigureMatch } from "@/lib/figure-match";
import type { Figure } from "@/types";

type Stage="IDLE"|"SCANNING"|"RESULTS"|"MANUAL";
function suggestedName(text:string){return text.split(/\r?\n/).map(line=>line.replace(/[^\p{L}\p{N}&'().:+ -]/gu," ").replace(/\s+/g," ").trim()).filter(line=>line.length>=3&&line.length<=90&&!/(warning|choking|hazard|ages? \d|made in|copyright)/i.test(line)).sort((a,b)=>Number(/[a-z]/.test(a))-Number(/[a-z]/.test(b))||b.length-a.length)[0]||""}
function filenameClue(fileName:string){const value=fileName.replace(/\.[^.]+$/,"").replace(/[_-]+/g," ").replace(/\b(?:img|image|photo|picture|screenshot|capture|download|whatsapp|copy)\b/gi," ").replace(/\b\d{8,}\b/g," ").replace(/\s+/g," ").trim();return value.length>=3?value:""}
async function compressedCapture(file:File){
  if(file.size<=2*1024*1024)return file;
  try{const bitmap=await createImageBitmap(file);const ratio=Math.min(1,1600/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement("canvas");canvas.width=Math.round(bitmap.width*ratio);canvas.height=Math.round(bitmap.height*ratio);canvas.getContext("2d")?.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,"image/jpeg",.84));return blob?new File([blob],`${file.name.replace(/\.[^.]+$/,"")}.jpg`,{type:"image/jpeg"}):file}catch{return file}
}

export function FigureCaptureMatcher({figures,userId,requesterUsername,onSelect}:{figures:Figure[];userId:string;requesterUsername:string;onSelect:(figure:Figure)=>void}){
  const inputRef=useRef<HTMLInputElement>(null);const [file,setFile]=useState<File|null>(null);const [preview,setPreview]=useState("");const [stage,setStage]=useState<Stage>("IDLE");const [scanPhase,setScanPhase]=useState<"OCR"|"VISION">("OCR");const [ocrText,setOcrText]=useState("");const [ocrConfidence,setOcrConfidence]=useState(0);const [visualMatches,setVisualMatches]=useState<RankedFigureMatch[]>([]);const [visionUsed,setVisionUsed]=useState(false);const [progress,setProgress]=useState(0);const [error,setError]=useState("");const [busy,setBusy]=useState(false);
  const [name,setName]=useState("");const [franchise,setFranchise]=useState("");const [manufacturer,setManufacturer]=useState("");const [notes,setNotes]=useState("");
  const matches=useMemo(()=>{const combined=new Map<string,RankedFigureMatch>();for(const item of [...visualMatches,...rankFigureMatches(ocrText,figures)]){const current=combined.get(item.figure.id);combined.set(item.figure.id,current?{...item,score:Math.max(current.score,item.score),evidence:[...new Set([...current.evidence,...item.evidence])].slice(0,5)}:item)}return [...combined.values()].sort((a,b)=>b.score-a.score).slice(0,5)},[ocrText,figures,visualMatches]);
  useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview)},[preview]);
  const scan=async(selected:File)=>{
    if(!selected.type.startsWith("image/")||selected.size>12*1024*1024){setError("Use a clear image no larger than 12 MB.");return}
    if(preview)URL.revokeObjectURL(preview);const imageUrl=URL.createObjectURL(selected);setFile(selected);setPreview(imageUrl);setStage("SCANNING");setScanPhase("OCR");setProgress(0);setError("");setOcrText("");setVisualMatches([]);setVisionUsed(false);
    let worker:Awaited<ReturnType<typeof import("tesseract.js")["createWorker"]>>|null=null;
    let text="";let confidence=0;
    try{const {createWorker}=await import("tesseract.js");worker=await createWorker("eng",undefined,{logger:message=>{if(message.status==="recognizing text")setProgress(Math.round(message.progress*100))}});const result=await worker.recognize(selected,{rotateAuto:true});text=result.data.text.trim();confidence=Math.round(result.data.confidence)}catch{}finally{await worker?.terminate().catch(()=>undefined)}
    const fileClue=filenameClue(selected.name);const identificationClues=[text,fileClue].filter(Boolean).join("\n");setOcrText(identificationClues);setOcrConfidence(confidence);const first=suggestedName(text||fileClue);setName(first);setNotes(text?`Packaging OCR: ${text.replace(/\s+/g," ").slice(0,500)}`:fileClue?`Captured image clue: ${fileClue}`:"");
    const textMatches=rankFigureMatches(identificationClues,figures);if(confidence<55||(textMatches[0]?.score||0)<.58){setScanPhase("VISION");setProgress(1);setVisionUsed(true);try{const visual=await rankFiguresVisually(imageUrl,figures,setProgress);setVisualMatches(visual);if(!first&&visual[0]){setName(visual[0].figure.character||visual[0].figure.name);setFranchise(visual[0].figure.franchise);setManufacturer(visual[0].figure.manufacturer)}}catch{if(!identificationClues)setError("Visual matching could not load. Retake with the box or product name visible, or add the figure manually.")}}
    setStage("RESULTS");
  };
  const selectMatch=(figure:Figure)=>{onSelect(figure);setStage("RESULTS")};
  const createCaptured=async()=>{
    if(!file||busy)return;setBusy(true);setError("");
    const finalName=name.trim()||filenameClue(file.name)||"Unidentified figure";const finalFranchise=franchise.trim()||"Unknown";
    try{if(!auth?.currentUser)throw new Error("Sign in before adding a figure.");const uploadFile=await compressedCapture(file);const token=await auth.currentUser.getIdToken();const safeName=uploadFile.name.replace(/[^a-zA-Z0-9._-]/g,"-");const blob=await upload(`images/${userId}/${crypto.randomUUID()}-${safeName}`,uploadFile,{access:"private",handleUploadUrl:"/api/blob/upload",headers:{Authorization:`Bearer ${token}`},contentType:uploadFile.type});const imageUrl=`/api/blob?pathname=${encodeURIComponent(blob.pathname)}`;const result=await createCommunityFigure({requesterId:userId,requesterUsername,name:finalName,franchise:finalFranchise,manufacturer:manufacturer.trim(),notes:notes.trim()||"Captured by collector for catalogue identification.",image:imageUrl,images:[imageUrl],imagePathnames:[blob.pathname]});onSelect({id:result.figureId,slug:result.slug,name:finalName,franchise:finalFranchise,character:finalName,manufacturer:manufacturer.trim(),series:"",scale:"",releaseYear:0,description:notes.trim(),image:imageUrl,images:[imageUrl],imagePathnames:[blob.pathname],verificationStatus:"COMMUNITY",moderationStatus:"PENDING"});setStage("RESULTS")}catch(reason){setError(reason instanceof Error?reason.message:"The captured figure could not be added.")}finally{setBusy(false)}
  };
  return <section className={`figure-scanner stage-${stage.toLowerCase()}`} aria-live="polite">
    <div className="scanner-head"><span><ScanText/><strong>Scan to identify</strong><small>Matches TinkerTown first; confirmed new scans improve future results</small></span>{file&&<button type="button" onClick={()=>inputRef.current?.click()}><RotateCcw/>Retake</button>}</div>
    {!file?<button type="button" className="scanner-capture" onClick={()=>inputRef.current?.click()}><span><Camera/></span><strong>Capture the figure or its box</strong><small>Keep the logo, character name and product line in frame.</small><em><ImagePlus/>Take photo or choose image</em></button>:<div className="scanner-workbench"><div className="scanner-preview"><Image unoptimized src={preview} alt="Captured figure" fill sizes="260px"/><span className="scan-rail"/></div><div className="scanner-results">
      {stage==="SCANNING"&&<div className="scan-status"><Sparkles/><strong>{scanPhase==="VISION"?"Recognizing the figure…":"Reading packaging…"}</strong><span><i style={{width:`${progress}%`}}/></span><small>{scanPhase==="VISION"?"First visual scan downloads the private on-device model":"OCR and image clues are checked first"}</small></div>}
      {stage==="RESULTS"&&<><div className="scan-summary"><span><Check/>{visionUsed?"Visual and text check complete":ocrConfidence>0?"Packaging text checked":"Image clues checked"}</span><small>{visionUsed?"Collector confirmation required":ocrConfidence>0?`${ocrConfidence}% text confidence`:"No readable text in photo"}</small></div>{matches.length?<><p>Choose the best catalogue match</p><div className="ocr-match-list">{matches.map(item=><button type="button" key={item.figure.id} onClick={()=>selectMatch(item.figure)}><span className="catalogue-thumb"><Image src={item.figure.image||"/tinkertown-mark.svg"} alt="" fill sizes="46px"/></span><span><strong>{item.figure.name}</strong><small>{item.figure.manufacturer} · matched {item.evidence.join(", ")}</small></span><em>{Math.round(item.score*100)}%</em></button>)}</div></>:<div className="scan-empty"><strong>No confident catalogue match</strong><small>Retake from the front with the figure fully visible, or add it manually.</small></div>}<button type="button" className="scanner-fallback" onClick={()=>setStage("MANUAL")}><PlusCircle/>Not here? Add captured figure</button></>}
      {stage==="MANUAL"&&<div className="captured-figure-form"><div><ShieldCheck/><span><strong>Use this photo now</strong><small>Everything below is optional. TinkerTown can hold it for catalogue review.</small></span></div><label><span>Figure name <em>Optional</em></span><input className="field" value={name} onChange={event=>setName(event.target.value)} placeholder="Use the packaging name if you know it"/></label><div className="form-row"><label><span>Franchise <em>Optional</em></span><input className="field" value={franchise} onChange={event=>setFranchise(event.target.value)} placeholder="Marvel, DC, Pokémon…"/></label><label><span>Manufacturer <em>Optional</em></span><input className="field" value={manufacturer} onChange={event=>setManufacturer(event.target.value)} placeholder="Hot Toys, Mattel…"/></label></div><label><span>Identifying details <em>Optional</em></span><textarea className="field" value={notes} onChange={event=>setNotes(event.target.value)} placeholder="Series, scale, release year or box markings"/></label><button type="button" className="btn btn-primary" disabled={busy} onClick={createCaptured}>{busy?"Adding captured figure…":"Use photo & continue"}</button></div>}
    </div></div>}
    <input ref={inputRef} className="sr-only" type="file" accept="image/*" capture="environment" onChange={event=>{const selected=event.target.files?.[0];event.target.value="";if(selected)void scan(selected)}}/>{error&&<p className="form-alert" role="alert">{error}</p>}
  </section>;
}
