"use client";

import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Bookmark, Boxes, ClipboardList, Grid2X2, Heart, LogOut, Package, Search, Settings, ShoppingBag, Store, UserRound, Users, X } from "lucide-react";
import { useFirestoreCollection } from "@/lib/firestore-data";
import type { Figure, Listing, UserProfile } from "@/types";

export function GlobalSearch({open,onClose}:{open:boolean;onClose:()=>void}){
  const inputRef=useRef<HTMLInputElement>(null);const dialogRef=useRef<HTMLDivElement>(null);const [query,setQuery]=useState("");
  const figures=useFirestoreCollection<Figure>(open?"figures":"",{limit:100}).data;
  const listings=useFirestoreCollection<Listing>(open?"listings":"",{where:[["status","==","ACTIVE"]],limit:100}).data;
  const collectors=useFirestoreCollection<UserProfile>(open?"users":"",{limit:100}).data;
  const needle=query.trim().toLowerCase();
  const figureResults=useMemo(()=>needle?figures.filter(item=>[item.name,item.character,item.franchise,item.manufacturer].some(value=>value?.toLowerCase().includes(needle))).slice(0,4):[],[figures,needle]);
  const listingResults=useMemo(()=>needle?listings.filter(item=>[item.title,item.seller,item.sellerName].some(value=>value?.toLowerCase().includes(needle))).slice(0,4):[],[listings,needle]);
  const collectorResults=useMemo(()=>needle?collectors.filter(item=>[item.displayName,item.username,item.location].some(value=>value?.toLowerCase().includes(needle))).slice(0,4):[],[collectors,needle]);
  const franchises=useMemo(()=>needle?[...new Set(figures.map(item=>item.franchise).filter(value=>value?.toLowerCase().includes(needle)))].slice(0,4):[],[figures,needle]);
  const close=useCallback(()=>{setQuery("");onClose()},[onClose]);
  useEffect(()=>{if(!open)return;document.body.style.overflow="hidden";const timer=setTimeout(()=>inputRef.current?.focus(),20);const key=(event:KeyboardEvent)=>{if(event.key==="Escape")close();if(event.key==="Tab"&&dialogRef.current){const items=Array.from(dialogRef.current.querySelectorAll<HTMLElement>('input,button,a[href]'));const first=items[0],last=items[items.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus()}}};document.addEventListener("keydown",key);return()=>{clearTimeout(timer);document.body.style.overflow="";document.removeEventListener("keydown",key)}},[close,open]);
  if(!open)return null;
  const hasResults=figureResults.length+listingResults.length+collectorResults.length+franchises.length>0;
  return <div className="command-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)close()}}><div className="command-panel" role="dialog" aria-modal="true" aria-label="Search TinkerTown" ref={dialogRef}><div className="command-input"><Search size={21}/><input ref={inputRef} value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search TinkerTown…" aria-label="Search TinkerTown"/><kbd>ESC</kbd><button onClick={close} aria-label="Close search"><X size={19}/></button></div><div className="command-body">{!needle?<><div className="command-hint"><strong>Explore TinkerTown</strong><span>Search figures, listings, collectors, and franchises from one place.</span></div><div className="command-shortcuts"><Link href="/catalogue" onClick={close}><Grid2X2/><span><strong>Figures</strong><small>Browse the master catalogue</small></span></Link><Link href="/marketplace" onClick={close}><Store/><span><strong>Listings</strong><small>Shop collector listings</small></span></Link><Link href="/discover" onClick={close}><Users/><span><strong>Collectors</strong><small>Find people and shelf stories</small></span></Link></div></>:hasResults?<div className="command-results">{figureResults.length>0&&<ResultGroup label="Figures">{figureResults.map(item=><Link key={item.id} href={`/figures/${item.slug}`} onClick={close}><Image src={item.image} alt="" width={42} height={42}/><span><strong>{item.name}</strong><small>{item.franchise} · {item.manufacturer}</small></span><Grid2X2/></Link>)}</ResultGroup>}{listingResults.length>0&&<ResultGroup label="Listings">{listingResults.map(item=><Link key={item.id} href={`/marketplace/listings/${item.id}`} onClick={close}><Image src={item.image} alt="" width={42} height={42}/><span><strong>{item.title}</strong><small>Marketplace · @{item.seller}</small></span><Store/></Link>)}</ResultGroup>}{collectorResults.length>0&&<ResultGroup label="Collectors">{collectorResults.map(item=><Link key={item.uid} href={`/profile/${item.username}`} onClick={close}><Image className="avatar" src={item.avatar||"/tinkertown-mark.svg"} alt="" width={42} height={42}/><span><strong>{item.displayName}</strong><small>@{item.username}</small></span><UserRound/></Link>)}</ResultGroup>}{franchises.length>0&&<ResultGroup label="Franchises">{franchises.map(item=><Link key={item} href={`/catalogue?q=${encodeURIComponent(item)}`} onClick={close}><span className="command-letter">{item.slice(0,1)}</span><span><strong>{item}</strong><small>Explore franchise figures</small></span><Boxes/></Link>)}</ResultGroup>}</div>:<div className="command-empty"><Search size={30}/><h2>No results for “{query}”</h2><p>Try a figure name, franchise, seller, or collector username.</p><Link href={`/search?q=${encodeURIComponent(query)}`} onClick={close}>Open full search</Link></div>}</div><footer className="command-footer"><span><kbd>↵</kbd> Open</span><span><kbd>↑</kbd><kbd>↓</kbd> Navigate</span><span><kbd>ESC</kbd> Close</span></footer></div></div>;
}

function ResultGroup({label,children}:{label:string;children:React.ReactNode}){return <section className="command-group"><h2>{label}</h2>{children}</section>}

type AccountUser={username?:string;displayName?:string;avatar?:string};
export function AccountMenu({user,logout}:{user:AccountUser;logout:()=>Promise<void>}){
  const [open,setOpen]=useState(false);const wrapRef=useRef<HTMLDivElement>(null);const router=useRouter();
  useEffect(()=>{if(!open)return;const close=(event:MouseEvent)=>{if(!wrapRef.current?.contains(event.target as Node))setOpen(false)};const key=(event:KeyboardEvent)=>{if(event.key==="Escape")setOpen(false)};document.addEventListener("mousedown",close);document.addEventListener("keydown",key);return()=>{document.removeEventListener("mousedown",close);document.removeEventListener("keydown",key)}},[open]);
  const profile=user.username?`/profile/${user.username}`:"/onboarding";
  const signOut=async()=>{setOpen(false);await logout();router.push("/login")};
  return <div className="account-menu-wrap" ref={wrapRef}><button className="account-trigger" onClick={()=>setOpen(value=>!value)} aria-label="Open account menu" aria-expanded={open}><Image className="avatar" src={user.avatar||"/tinkertown-mark.svg"} alt="" width={42} height={42}/></button>{open&&<div className="account-menu" role="menu"><header><Image className="avatar" src={user.avatar||"/tinkertown-mark.svg"} alt="" width={44} height={44}/><span><strong>{user.displayName||"Collector"}</strong><small>@{user.username||"collector"}</small></span></header><nav><Link onClick={()=>setOpen(false)} role="menuitem" href={profile}><UserRound/>View Profile</Link><Link onClick={()=>setOpen(false)} role="menuitem" href="/collection"><Package/>My Collection</Link><Link onClick={()=>setOpen(false)} role="menuitem" href="/wishlist"><Heart/>Wishlist</Link><Link onClick={()=>setOpen(false)} role="menuitem" href="/saved"><Bookmark/>Saved Posts</Link><Link onClick={()=>setOpen(false)} role="menuitem" href="/marketplace/selling"><ClipboardList/>My Listings</Link><Link onClick={()=>setOpen(false)} role="menuitem" href="/orders"><ShoppingBag/>Orders</Link></nav><div className="account-divider"/><nav><Link onClick={()=>setOpen(false)} role="menuitem" href="/settings/profile"><Settings/>Settings</Link><button role="menuitem" onClick={signOut}><LogOut/>Sign Out</button></nav></div>}</div>;
}
